version: '3.8'

services:
  redis:
    image: redis
    container_name: redis-microservice-server
    ports:
      - "6379:6379"
    volumes:
      - ./redis-service/config/redis.conf:/redis.conf
    command: ["redis-server", "/redis.conf"]

  db:
    container_name: leonardo
    image: postgres:14
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: leonardo
    ports:
      - "5431:5432"
    volumes:
      - ./setup.sql:/docker-entrypoint-initdb.d/setup.sql
      - pgdata:/var/lib/postgresql/data

  pgadmin:  
    image: dpage/pgadmin4
    restart: always
    container_name: nest-pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin4
    ports:
      - '5050:80'
    depends_on:
      - db

  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: task-scheduler
  #   environment:
  #     - PORT=3002
  #   depends_on:
  #     - db
  #     - redis
  #   volumes:
  #     - ./src:/app/src


volumes:
  cache:
    driver: local
  pgdata:
